---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 60m
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 60m
  releaseName: tf-controller
  chart:
    spec:
      chart: tf-controller
      version: 0.16.0-rc.3
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      interval: 10m